# Number of days of inactivity before an issue becomes stale
daysUntilStale: 30
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
#exemptLabels:
#  - wontfix
# Label to use when marking an issue as stale
staleLabel: stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue/PR has been automatically marked as stale because it has not had any update (including
  commits, comments, labels, milestones, etc) for 30 days. It will be closed automatically if no
  further update occurs in 7 day. Thank you for your contributions!
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
